name: modrinth-publish

run-name: Build ${{inputs.placeholder_variable_for_project_slug}} ${{outputs.placeholder_variable_for_build_version}} (${{inputs.placeholder_variable_for_build_type}}) [${{outputs.placeholder_variable_for_mc_version_tag}}]

on:
  workflow_dispatch:
    inputs:
      VARIABLE_1:
        description: 'Which project would you like to publish?'
        required: true
        type: